name: assignment_pro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.0
  flutter_svg: ^2.0.10
  dartz: ^0.10.1
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.15
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

